# Copyright (c) 2018 Bitwise IO, Inc.
# Licensed under Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/
version: "2.1"

services:
  jekyll:
    image: generator-jekyll
    build: ./generator
    working_dir: /srv/jekyll/
    entrypoint: /srv/jekyll/entrypoint-gen.sh
    volumes:
      - $PWD/generator:/srv/jekyll
  linter:
    image: linter
    build: ./linter
    volumes:
      - $PWD/generator:/srv/jekyll
    working_dir: /srv/jekyll/
    entrypoint: /srv/jekyll/entrypoint-lint.sh
  webserver:
    image: sawtooth-website
    container_name: sawtooth-website
    build:
      context: .
      dockerfile: webserver/Dockerfile
    working_dir: /srv/jekyll/
    entrypoint: /srv/jekyll/entrypoint-web.sh
    expose:
      - 80
    ports:
      - 8000:80
    volumes:
      - $PWD/generator:/srv/jekyll
    environment:
      - BUILDONLY=${BUILDONLY}
